### ISSUE TITLE
Naming JavaScript and CoffeeScript files the same thing

### ISSUE THREAD

**Issue by searls** [johnbintz/jasmine-headless-webkit#110]
So, I realize this isn't typical, but I have two files in my spec dir:

```
spec/
├── jasmine-given-spec.coffee
├── jasmine-given-spec.js
```

When I do this, I get erratic test output. One of two things happen, by chance:
1. The coffee spec runs, the JavaScript does not run
2. Neither runs (0 specs run)

In neither case will the JavaScript spec run.

Once I renamed one of the files, everything ran (and consistently):

```
spec/
├── jasmine-given-js-spec.js
├── jasmine-given-spec.coffee

```

**Comment by johnbintz** [comment]
What would you expect the behavior to be?

**Comment by searls** [comment]
I would expect JHW to run both spec files like any other two
differently-named spec files. I may be conveying this poorly,
apologies.

On Jan 12, 2012, at 13:35, John Bintz
reply@reply.github.com
wrote:

**Comment by johnbintz** [comment]
All right, I'll add a scenario for this condition and look into it in a bit.

**Comment by johnbintz** [comment]
The issue was how I was comparing assets to each other to prevent multiple inclusion of files. I was comparing the logical path of the asset (in your case, `jasmine-given-spec`) to already-included assets, which means anything with the same signature will only get included once. I'm about to push a change that will instead compare the full paths of each asset. Let me know if this works better for you.
