### ISSUE TITLE
window.document is shared between tests

### ISSUE THREAD

**Issue by samwgoldman** [johnbintz/jasmine-headless-webkit#124]
I would like to use this to test javascript that depends on modifications to the document, specifically, adding elements to window.document.body.

I noticed that my modifications we persisting between tests. Is this a bug or is this expected behavior? Is there a workaround?

**Comment by johnbintz** [comment]
This is expected behavior, since Jasmine itself has no knowledge of the environment it runs within, just that it has to manage specs and expectations. You'll have to do cleanup outside of the Jasmine environment yourself. Might I suggest using [`jasmine-jquery`](http://github.com/velesin/jasmine-jquery) to set up fixtures to run your DOM manipulation tests within?

**Comment by samwgoldman** [comment]
Makes sense. Thanks!
