### ISSUE TITLE
Console.log forces an unsuccessful return code

### ISSUE THREAD

**Issue by mcolyer** [johnbintz/jasmine-headless-webkit#147]
If any of your tests output to the console using `console.log` then the return code of JHW will be not be 0 even if all of the tests pass. 

While it may seem small, it turns out to be rather annoying as we use JHW in a CI environment which causes our builds to fail even when they haven't. For now we've just eliminated all of our console logging statements.

I believe this was the cause of #121 but I don't have a way to confirm that hunch.

**Comment by johnbintz** [comment]
This is by design. Any use of `console.log` returns 2 as an indication that you may be using `console.log` in code that will be used by the browser, which can cause problems for end users. Removing the `console.log`s from your code and tests is the right approach, so that none inadvertently slip in to code for end users.

**Comment by hlascelles** [comment]
Can we make this configurable? We deliberately log to a logger that only sends it to the console in test.

**Comment by hlascelles** [comment]
Pull request sent: https://github.com/johnbintz/jasmine-headless-webkit/pull/157
