### ISSUE TITLE
Cannot fetch file via AJAX

### ISSUE THREAD

**Issue by jamesarosen** [johnbintz/jasmine-headless-webkit#2]
Running `jasmine-headless-webkit path/to/jasmine.yml` just causes a large number of the following statements to be printed to STDOUT, regardless of whether I'm running the Jasmine server or not:

> [console] ">> Jasmine waiting for initial fetch to complete"

System:
- Mac OS X
- Qt 4.7.2
- Ruby 1.9.2p180
- jasmine-headless-webkit 0.0.2
- jasmine 1.0.2.0

**Comment by jamesarosen** [comment]
Sorry, I posted that before I had finished explaining. That message comes from one of my specs:

```
initialFetchComplete = false;
user.fetch({success: function() {initialFetchComplete = true;}});
waitsFor(function() {
  return initialFetchComplete;
}, 'initial fetch to complete');
```

The test passes on regular WebKit, Firefox and IE8. What's failing is an AJAX get to `/__spec__/some/file.json`, which is a path that works in the normal Jasmine server.

**Comment by johnbintz** [comment]
Since the spec runner doesn't boot up the Jasmine server and run the specs in that context, the runner will never be able to get to any file that's supposed to be delivered from the server. In the cases where I've needed to test server interaction so that it works both in the WebKit runner and in the browser, I've used Sinon to mock out the server calls with a lot of success: http://sinonjs.org/docs/#server

If you did want to run your specs headless against a running Jasmine server, you could also use the PhantomJS method: http://code.google.com/p/phantomjs/wiki/ServiceIntegration

**Comment by jamesarosen** [comment]
Jasmine seems to work great, thanks :)
