### ISSUE TITLE
qmake instructions for Ubuntu should mention update-alternatives

### ISSUE THREAD

**Issue by logankoester** [johnbintz/jasmine-headless-webkit#61]
For 11.04 it was not enough to simply `sudo apt-get install libqt4-dev qt4-qmake`, I then also had to `sudo update-alternatives --config qmake` and choose Qt4 interactively from the list.

The documentation should mention this step.

**Comment by johnbintz** [comment]
What are the other choices for `update-alternatives --config qmake` on your system? With the "other" `qmake` chosen, what did `qmake --version` report?

I run Kubuntu 11.04 and didn't have this issue, since I only had the newest Qt 4 library installed. I just want to know how to let users know if they need to perform this step and how to check for it.

**Comment by logankoester** [comment]
It makes some sense that you'd have a newer Qt with Kubuntu than Ubuntu. I think this issue probably exists on systems that have been upgraded from a previous Ubuntu, but I can't really verify that. You know you need to do it if `qmake --version` still shows the old Qt version after running `apt-get`.

Sorry I can't help more than that, the machine I'm on today already has the latest qmake set up.

**Comment by johnbintz** [comment]
OK, just wanted to get a better idea. I'll add it to the docs for this next release (next week, hoepfully). Thanks!

**Comment by johnbintz** [comment]
It's in the docs. Let me know if I missed anything.
