### ISSUE TITLE
If overall test suite takes >5 secs, errors and exits.

### ISSUE THREAD

**Issue by sarenji** [johnbintz/jasmine-headless-webkit#76]
We're trying out jasmine-headless-webkit at work, and it's working great on our Mac Mini (OS X 10.7). The entire test suite takes about 4.6 seconds to complete.

However, when we ran the tests on our much slower personal laptops, our tests would output `WARNING: too many runs and the test is still not finished!` at some point (about 5-8 seconds) and exit, not running the rest of the tests.

On the Mac Mini (OS X 10.7), when I made a copy of all the tests to increase the test completion time, it gave the above error and timed out when it normally didn't.

On our personal MacBook Airs (OS X 10.6), when I deleted half the tests, it took less than <5 seconds and the suite completed.

Any ideas? Does having a test suite that takes longer than 5 seconds to complete work on Linux?

**Comment by johnbintz** [comment]
It's actually because of a "dead man's switch" in the code to make sure the runner doesn't spiral out of control. (along with a ton of other changes) I've make it so that every time a spec finishes, it pings the runner to reset the countdown of the switch. Try the current git HEAD and let me know if that (and those other runner changes) work for you.

**Comment by sarenji** [comment]
HEAD works just fine on all computers now. Great!

`PASS: 273 tests, 0 failures, 20.137 secs.`

**Comment by johnbintz** [comment]
Sweet. :) 0.8.0 will be released once I get one additional piece added this week or next.
