### ISSUE TITLE
Option for randomizing spec order

### ISSUE THREAD

**Issue by christiannelson** [johnbintz/jasmine-headless-webkit#78]
Just bitten by a bug in specs that accidentally relied on the order in which they were run. It'd be great if we could randomize the order that specs are run to unearth these cases more quickly.

**Comment by johnbintz** [comment]
Sounds like a good idea. I'm reworking the entire file loading system for the next release. I'll see if I can squeeze it in.

**Comment by johnbintz** [comment]
There's a bunch of other Sprockets stuff along with it, but I do have spec randomization in on HEAD master branch. I don't have an option to turn it off just yet, since upon thinking about it, load order for specs really shouldn't matter. If folks complain, I'll add an actual switch to turn it on/off. Take it for a spin.

**Comment by christiannelson** [comment]
Took it for a spin and it looks like it's working nicely. Thanks!

FYI, check this for rspec's ordering configuring: http://blog.davidchelimsky.net/2011/11/06/rspec-280rc1-is-released

And this for minitest's: http://www.bootspring.com/2010/09/22/minitest-rubys-test-framework/

The short version is that they both allow you to recreate an order by passing a seed value, which may be helpful when debugging.

**Comment by johnbintz** [comment]
Try the latest HEAD. It supports --seed much like RSpec and others.

**Comment by johnbintz** [comment]
Just used it on a spec dependency issue and it works perfectly. Closing.
